name       : antlr4-cpp-runtime
version    : 4.7.1
release    : 1
source     :
    - http://www.antlr.org/download/antlr4-cpp-runtime-4.7.1-source.zip : 23bebc0411052a260f43ae097aa1ab39869eb6b6aa558b046c367a4ea33d1ccc
license    :
    - BSD-3-Clause
    - MIT
component  : programming.library
summary    : C++ Runtime for ANTLR4
description: |
    C++ Runtime for ANTLR4
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    mv $installdir/usr/lib{,64}